// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKX0Nop783sl2SXyelImkrb-ya7HGhsJM',
    appId: '1:738615375120:web:4ef9504d15c99b2ffe6195',
    messagingSenderId: '738615375120',
    projectId: 'product-app-9a710',
    authDomain: 'product-app-9a710.firebaseapp.com',
    storageBucket: 'product-app-9a710.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8CG7LV_7PPlkBE_F2zXrnZ9VzShzYtq0',
    appId: '1:738615375120:android:dad9a89f65dd3af6fe6195',
    messagingSenderId: '738615375120',
    projectId: 'product-app-9a710',
    storageBucket: 'product-app-9a710.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWQ7QGdIB5XtsIIk9iHdexc82kfKPjIFc',
    appId: '1:738615375120:ios:ceee508eaf41a9effe6195',
    messagingSenderId: '738615375120',
    projectId: 'product-app-9a710',
    storageBucket: 'product-app-9a710.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWQ7QGdIB5XtsIIk9iHdexc82kfKPjIFc',
    appId: '1:738615375120:ios:ceee508eaf41a9effe6195',
    messagingSenderId: '738615375120',
    projectId: 'product-app-9a710',
    storageBucket: 'product-app-9a710.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKX0Nop783sl2SXyelImkrb-ya7HGhsJM',
    appId: '1:738615375120:web:ae2b67623c845872fe6195',
    messagingSenderId: '738615375120',
    projectId: 'product-app-9a710',
    authDomain: 'product-app-9a710.firebaseapp.com',
    storageBucket: 'product-app-9a710.firebasestorage.app',
  );
}
